version: '2'

services: 
  centreon-central:
    build: ./
    image: centreon-central
    container_name: centreon-central
    privileged: true
    environment:
      - PHP_DATE_TIMEZONE=Europe/Paris
    links: 
      - db:db
    ports: 
      - "8080:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      
  db:
    image: mariadb
    container_name: centreon-db
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db-data:/var/lib/mysql

volumes: 
  db-data: