version: '3'
services: 
  centreon-central:
    build: ./
    image: centreon-central
    container_name: kbeaugrand/centreon-central
    privileged: true
    environment:
      - PHP_DATE_TIMEZONE=Europe/Paris
    links: 
      - db:db
    ports: 
      - "8080:80"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - centreon-engine-config:/etc/centreon-engine
      - centreon-broker-config:/etc/centreon-broker
      
  db:
    image: mariadb
    container_name: centreon-db
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db-data:/var/lib/mysql

volumes: 
  db-data:
  centreon-engine-config:
  centreon-broker-config:
