version: '3'
volumes: 
  db-data:

services: 
  centreon-central:
    build: ./
    environment:
      - PHP_DATE_TIMEZONE=Europe/Paris
    links: 
      - db:db
  db:
    image: mariadb
    environment: 
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - db-data:/var/lib/mysql